# Development Docker Compose configuration
version: '3.8'

services:
  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: science-paper-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Test Redis instance
  redis-test:
    image: redis:7-alpine
    container_name: science-paper-redis-test
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    command: redis-server --appendonly yes --port 6379
    profiles:
      - testing

  # Development web application with hot reload
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: science-paper-web-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - WEBSOCKET_PORT=3001
      - DEBUG_MODE=true
    env_file:
      - .env.local
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - dev_backup_data:/var/backups/science-paper-manager
      - dev_log_data:/var/log
    command: npm run dev
    profiles:
      - development

  # Development worker with hot reload
  worker-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: science-paper-worker-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - WORKER_CONCURRENCY=2
      - DEBUG_MODE=true
    env_file:
      - .env.local
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - dev_log_data:/var/log
    command: npm run worker:dev
    profiles:
      - development

volumes:
  redis_dev_data:
    driver: local
  redis_test_data:
    driver: local
  dev_backup_data:
    driver: local
  dev_log_data:
    driver: local

networks:
  default:
    name: science-paper-dev-network